export {IActivity, ISeance} from './Activity';
export {IActivityOrder, IActivityProduct} from './ActivityOrder';
export {IAdisyon, IAdisyonProduct} from './Adisyon';
export {IConfig} from './Config';
export {ICustomer, ICustomerFreeItems, ICustomerTrans} from './Customer';
export {IDepartment} from './Department';
export {IEcr} from './Ecr';
export {IExchange} from './Exchange';
export {IGarson} from './Garson';
export {Result} from './Result';
export {IStok} from './Stok';
export {IStokGrup} from './StokGrup';
export {ITable} from './Table';
export {IUser} from './User';
